### ISSUE TITLE
Cannot use BigList, import error.

### ISSUE THREAD

**Issue by dougg0k** [marcocesarato/react-native-big-list#3]
```error: Error: Unable to resolve module ./BigList from /node_modules/react-native-big-list/lib/index.js: 

None of these files exist:
  * node_modules/react-native-big-list/lib/BigList(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules/react-native-big-list/lib/BigList/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
> 1 | import BigList from "./BigList";
    |                      ^
  2 |
  3 | export default BigList;
  4 |
    at ModuleResolver.resolveDependency (/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:211:15)
    at DependencyGraph.resolveDependency (/node_modules/metro/src/node-haste/DependencyGraph.js:413:43)
    at Object.resolve (/node_modules/metro/src/lib/transformHelpers.js:317:42)
    at resolve (/node_modules/metro/src/DeltaBundler/traverseDependencies.js:629:33)
    at /node_modules/metro/src/DeltaBundler/traverseDependencies.js:645:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/node_modules/metro/src/DeltaBundler/traverseDependencies.js:644:33)
    at /node_modules/metro/src/DeltaBundler/traverseDependencies.js:329:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/node_modules/metro/src/DeltaBundler/traverseDependencies.js:137:24)```

**Comment by ydv0121** [comment]
+1

**Comment by marcocesarato** [comment]
Hi, it probably appears because in the configuration the `.jsx` file extension is not resolved (as you can see from the options shown after` None of these files exist` `.jsx` extension is missing).
I added a bundler to the library to compile it and rename all files to `js` to make it compatible with`module` and `commonjs` on multi-environment. This is still available in version `1.2.1`.

Thanks for reporting this issues.

**Comment by ydv0121** [comment]
still same issue @marcocesarato
its working after i manually rename all files `.jsx` to `.js`

**Comment by marcocesarato** [comment]
Hi @ydv0121, I forced the usage of the new distribution on release `1.2.3`.

Let me know if now it works.

**Comment by ydv0121** [comment]
@marcocesarato yes its working on `1.2.3` release.
Thank you

**Comment by dougg0k** [comment]
Thanks!
